
import {
  HomeIcon,
  ShoppingCartIcon,
  UsersIcon,
  CalendarDaysIcon,
  WrenchIcon,
  Cog6ToothIcon,
  BuildingOfficeIcon,
  MagnifyingGlassIcon,
  BellIcon,
  UserCircleIcon,
  PencilIcon,
  PlusIcon,
  TrashIcon,
  ChevronLeftIcon,  
  ChevronRightIcon, 
} from '@heroicons/react/24/solid';

export {
  HomeIcon,
  ShoppingCartIcon,
  UsersIcon,
  CalendarDaysIcon,
  WrenchIcon,
  Cog6ToothIcon,
  BuildingOfficeIcon,
  MagnifyingGlassIcon,
  BellIcon,
  UserCircleIcon,
  PencilIcon,
  PlusIcon,
  TrashIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
};